[2021-06-02 12:03:36.215] [renderer3] [warning] Workbench did not finish loading in 10 seconds, that might be a problem that should be reported.
[2021-06-02 12:03:55.704] [renderer3] [info] [remote-connection][ExtensionHost][d11c2…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-06-02 12:03:55.704] [renderer3] [info] [remote-connection][ExtensionHost][d11c2…][reconnect] waiting for 5 seconds before reconnecting...
[2021-06-02 12:03:56.712] [renderer3] [info] [remote-connection][Management   ][5950d…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-06-02 12:03:56.724] [renderer3] [info] [remote-connection][Management   ][5950d…][reconnect] waiting for 5 seconds before reconnecting...
[2021-06-02 12:04:00.704] [renderer3] [info] [remote-connection][ExtensionHost][d11c2…][reconnect] resolving connection...
[2021-06-02 12:04:01.721] [renderer3] [info] [remote-connection][Management   ][5950d…][reconnect] resolving connection...
[2021-06-02 12:04:01.723] [renderer3] [info] [remote-connection][ExtensionHost][d11c2…][reconnect] A promise cancelation error occurred while trying to reconnect, will try again...
[2021-06-02 12:04:01.723] [renderer3] [info] [remote-connection][ExtensionHost][d11c2…][reconnect] waiting for 5 seconds before reconnecting...
[2021-06-02 12:04:02.400] [renderer3] [error] [remote-connection][Management   ][5950d…][reconnect] An unknown error occurred while trying to reconnect, since this is an unknown case, it will be treated as a permanent error! Will give up now! Error:
[2021-06-02 12:04:02.400] [renderer3] [error] Error
    at e.resolveAuthority (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:4885:869)
    at async F._resolveAuthorityAgain (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:5440:886)
[2021-06-02 12:04:06.724] [renderer3] [error] [remote-connection][ExtensionHost][d11c2…][reconnect] permanent failure occurred while running the reconnecting loop.
